name: ci

on:
  push:
    branches: [ main, integration-tests, edge ]
  pull_request:
    branches: [ main, edge ]

jobs:
  e2e-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # pin@v3
        with:
          node-version: '19'

      - run: npm install

      - name: Setup Kubernetes
        uses: engineerd/setup-kind@aa272fe2a7309878ffc2a81c56cfe3ef108ae7d0 # pin@v0.5.0
        with:
          version: v0.17.0
          image: kindest/node:v1.23.13

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@2c7d650d4472bb7c92fa5fea86589527dfa5abcc # pin@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: extension test
        uses: GabrielBB/xvfb-action@86d97bde4a65fe9b290c0b3fb92c2c4ed0e5302d # pin@v1
        with:
          run: 'npm test'
          options: "-screen 0 1600x1200x24"
